### ISSUE TITLE
Closing bracket cursor is not visible

### ISSUE THREAD

**Issue by juliancoleman** [olivercederborg/poimandres.nvim#31]
In the screenshot below, the cursor is over the closing curly brace, but it does not appear there. You can see that Nvim has colored the bg of the matching bracket 2 lines above it.

![Screenshot 2023-03-15 at 9 36 46 AM](https://user-images.githubusercontent.com/11545939/225361703-ea9b4f8e-7335-4849-b920-3490a1f7a5ef.png)

Here's a list of all my installed packages for Nvim (I'm on latest version)
* wbthomason/packer.nvim
* olivercederborg/poimandres.nvim
* neovim/nvim-lspconfig
* hrsh7th/cmp-nvim-lsp
* hrsh7th/cmp-buffer
* hrsh7th/cmp-nvim-lua
* L3M0N4D3/LuaSnip
* saadparwaiz1/cmp_luasnip
* onsails/lspkind.nvim
* jiangmiao/auto-pairs
* numToStr/Comment.nvim
* nvim-telescope/telescope.nvim
* nvim-telescope/telescope-fzf-native.nvim
* gpanders/editorconfig.nvim
* prettier/vim-prettier
* nvim-treesitter/nvim-treesitter
* nvim-treesitter/nvim-treesitter-context
* lukas-reineke/indent-blankline.nvim

**Comment by juliancoleman** [comment]
I want to bump this issue. The last update (~30hrs ago) actually resolved the bracket issue in some instances, but it appears the issue is still persistent in others. Specifically, JSX props as objects, and React hook parentheses still have the issue. However, the top-level function component does not have this issue anymore.

**Comment by olivercederborg** [comment]
@juliancoleman What terminal are you using and what is your theme for the terminal?

**Comment by olivercederborg** [comment]
@juliancoleman I have pushed an update which touches highlights, so please let me know if this problem still persists 👏🏼

**Comment by juliancoleman** [comment]
Hey, @olivercederborg ! Thanks for the reply!

I am currently using Alacritty Terminal and here's a copy/pasta of my theme below.

```yaml
colors:
  # Default colors
  primary:
    background: "0x1b1e28"
    foreground: "0xa6accd"

  # Cursor colors
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  search:
    # Allowed values are CellForeground/CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    matches:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

    focused_match:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

    footer_bar:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  selection:
    text: CellForeground
    background: "0x303340"

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black: "0x1b1e28"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "0x89ddff"
    magenta: "0xfcc5e9"
    cyan: "0xadd7ff"
    white: "0xffffff"

  # Bright colors
  bright:
    black: "0xa6accd"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "0xadd7ff"
    magenta: "0xfae4fc"
    cyan: "0x89ddff"
    white: "0xffffff"
```

The issue is still persistent, and using the same terminal theme with other Nvim themes don't seem to have the same issue (although, they have other issues). It could be my theme, though!
